# Generated by Django 5.2.17 on 2026-09-20 13:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ReportSubscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('frequency', models.CharField(choices=[('WEEKLY', 'Weekly'), ('MONTHLY', 'Monthly')], max_length=10)),
                ('delivery_method', models.CharField(choices=[('EMAIL', 'Email'), ('API', 'API')], max_length=10)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('endpoint_url', models.URLField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('last_sent_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='report_subscriptions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['is_active', 'frequency'], name='report_active_freq_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(models.Q(('delivery_method', 'EMAIL'), ('email__isnull', False), ('endpoint_url__isnull', True)), models.Q(('delivery_method', 'API'), ('email__isnull', True), ('endpoint_url__isnull', False)), _connector='OR'), name='report_delivery_target_ck')],
            },
        ),
    ]
