# Generated by Django 5.2.17 on 2026-09-20 13:13

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        ('forms', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Process',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('process_type', models.CharField(choices=[('LINEAR', 'Linear'), ('FREE', 'Free')], max_length=10)),
                ('visibility', models.CharField(choices=[('PUBLIC', 'Public'), ('PRIVATE', 'Private')], default='PUBLIC', max_length=10)),
                ('access_password_hash', models.CharField(blank=True, max_length=128, null=True)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('PUBLISHED', 'Published'), ('CLOSED', 'Closed')], default='DRAFT', max_length=10)),
                ('view_count', models.PositiveBigIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='processes', to='core.category')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='owned_processes', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ProcessRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('resume_token_hash', models.CharField(blank=True, max_length=128, null=True)),
                ('status', models.CharField(choices=[('IN_PROGRESS', 'In progress'), ('COMPLETED', 'Completed')], default='IN_PROGRESS', max_length=16)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('process', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='runs', to='processes.process')),
                ('respondent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='process_runs', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ProcessStep',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField()),
                ('form', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='process_steps', to='forms.form')),
                ('process', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='steps', to='processes.process')),
            ],
        ),
        migrations.CreateModel(
            name='ProcessStepRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('LOCKED', 'Locked'), ('AVAILABLE', 'Available'), ('COMPLETED', 'Completed')], max_length=16)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('process_run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='step_runs', to='processes.processrun')),
                ('process_step', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='run_states', to='processes.processstep')),
                ('submission', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='process_step_run', to='forms.formsubmission')),
            ],
        ),
        migrations.AddIndex(
            model_name='process',
            index=models.Index(fields=['owner', 'status', '-created_at'], name='proc_owner_status_created_idx'),
        ),
        migrations.AddConstraint(
            model_name='process',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('access_password_hash__isnull', True), ('visibility', 'PUBLIC')), models.Q(('access_password_hash__isnull', False), ('visibility', 'PRIVATE')), _connector='OR'), name='process_visibility_password_ck'),
        ),
        migrations.AddIndex(
            model_name='processrun',
            index=models.Index(fields=['process', 'status', '-started_at'], name='proc_run_status_started_idx'),
        ),
        migrations.AddConstraint(
            model_name='processrun',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('respondent__isnull', False), ('resume_token_hash__isnull', True)), models.Q(('respondent__isnull', True), ('resume_token_hash__isnull', False)), _connector='OR'), name='proc_run_identity_xor_ck'),
        ),
        migrations.AddConstraint(
            model_name='processrun',
            constraint=models.UniqueConstraint(condition=models.Q(('resume_token_hash__isnull', False)), fields=('resume_token_hash',), name='proc_run_token_hash_uniq'),
        ),
        migrations.AddConstraint(
            model_name='processrun',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('completed_at__isnull', True), ('status', 'IN_PROGRESS')), models.Q(('completed_at__isnull', False), ('status', 'COMPLETED')), _connector='OR'), name='proc_run_status_completed_ck'),
        ),
        migrations.AddConstraint(
            model_name='processstep',
            constraint=models.UniqueConstraint(fields=('process', 'order'), name='process_step_order_uniq'),
        ),
        migrations.AddConstraint(
            model_name='processstep',
            constraint=models.UniqueConstraint(fields=('process', 'form'), name='process_step_form_uniq'),
        ),
        migrations.AddConstraint(
            model_name='processstep',
            constraint=models.CheckConstraint(condition=models.Q(('order__gte', 1)), name='process_step_order_gte_1_ck'),
        ),
        migrations.AddIndex(
            model_name='processsteprun',
            index=models.Index(fields=['process_run', 'status'], name='step_run_run_status_idx'),
        ),
        migrations.AddConstraint(
            model_name='processsteprun',
            constraint=models.UniqueConstraint(fields=('process_run', 'process_step'), name='step_run_run_step_uniq'),
        ),
        migrations.AddConstraint(
            model_name='processsteprun',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('completed_at__isnull', False), ('status', 'COMPLETED'), ('submission__isnull', False)), models.Q(('completed_at__isnull', True), ('status__in', ['LOCKED', 'AVAILABLE']), ('submission__isnull', True)), _connector='OR'), name='step_run_state_data_ck'),
        ),
    ]
