# Generated by Django 5.2.17 on 2026-09-29 13:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0001_initial'),
        ('processes', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='processrun',
            name='proc_run_identity_xor_ck',
        ),
        migrations.RemoveConstraint(
            model_name='processrun',
            name='proc_run_token_hash_uniq',
        ),
        migrations.RemoveConstraint(
            model_name='processrun',
            name='proc_run_status_completed_ck',
        ),
        migrations.RemoveConstraint(
            model_name='processsteprun',
            name='step_run_run_step_uniq',
        ),
        migrations.RemoveConstraint(
            model_name='processsteprun',
            name='step_run_state_data_ck',
        ),
        migrations.RemoveIndex(
            model_name='processrun',
            name='proc_run_status_started_idx',
        ),
        migrations.RemoveIndex(
            model_name='processsteprun',
            name='step_run_run_status_idx',
        ),
        migrations.RemoveField(
            model_name='processrun',
            name='public_id',
        ),
        migrations.AddField(
            model_name='processrun',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='processrun',
            name='status',
            field=models.CharField(choices=[('IN_PROGRESS', 'In Progress'), ('COMPLETED', 'Completed')], default='IN_PROGRESS', max_length=20),
        ),
        migrations.AlterField(
            model_name='processsteprun',
            name='process_step',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='runs', to='processes.processstep'),
        ),
        migrations.AlterField(
            model_name='processsteprun',
            name='status',
            field=models.CharField(choices=[('LOCKED', 'Locked'), ('AVAILABLE', 'Available'), ('COMPLETED', 'Completed')], default='LOCKED', max_length=20),
        ),
        migrations.AlterField(
            model_name='processsteprun',
            name='submission',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='step_runs', to='forms.formsubmission'),
        ),
        migrations.AlterUniqueTogether(
            name='processsteprun',
            unique_together={('process_run', 'process_step')},
        ),
        migrations.AddConstraint(
            model_name='processrun',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('respondent__isnull', False), ('resume_token_hash__isnull', True)), models.Q(('respondent__isnull', True), ('resume_token_hash__isnull', False)), _connector='OR'), name='process_run_xor_identity'),
        ),
    ]
