# Generated by Django 5.2.17 on 2026-09-29 13:17

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0001_initial'),
        ('processes', '0002_remove_processrun_proc_run_identity_xor_ck_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='processrun',
            name='process_run_xor_identity',
        ),
        migrations.AlterUniqueTogether(
            name='processsteprun',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='processrun',
            name='public_id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
        migrations.AlterField(
            model_name='processrun',
            name='status',
            field=models.CharField(choices=[('IN_PROGRESS', 'In progress'), ('COMPLETED', 'Completed')], default='IN_PROGRESS', max_length=16),
        ),
        migrations.AlterField(
            model_name='processsteprun',
            name='process_step',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='run_states', to='processes.processstep'),
        ),
        migrations.AlterField(
            model_name='processsteprun',
            name='status',
            field=models.CharField(choices=[('LOCKED', 'Locked'), ('AVAILABLE', 'Available'), ('COMPLETED', 'Completed')], default='LOCKED', max_length=16),
        ),
        migrations.AlterField(
            model_name='processsteprun',
            name='submission',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='process_step_runs', to='forms.formsubmission'),
        ),
        migrations.AddIndex(
            model_name='processrun',
            index=models.Index(fields=['process', 'status', '-started_at'], name='proc_run_status_started_idx'),
        ),
        migrations.AddIndex(
            model_name='processsteprun',
            index=models.Index(fields=['process_run', 'status'], name='step_run_run_status_idx'),
        ),
        migrations.AddConstraint(
            model_name='processrun',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('respondent__isnull', False), ('resume_token_hash__isnull', True)), models.Q(('respondent__isnull', True), ('resume_token_hash__isnull', False)), _connector='OR'), name='proc_run_identity_xor_ck'),
        ),
        migrations.AddConstraint(
            model_name='processrun',
            constraint=models.UniqueConstraint(condition=models.Q(('resume_token_hash__isnull', False)), fields=('resume_token_hash',), name='proc_run_token_hash_uniq'),
        ),
        migrations.AddConstraint(
            model_name='processrun',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('completed_at__isnull', True), ('status', 'IN_PROGRESS')), models.Q(('completed_at__isnull', False), ('status', 'COMPLETED')), _connector='OR'), name='proc_run_status_completed_ck'),
        ),
        migrations.AddConstraint(
            model_name='processsteprun',
            constraint=models.UniqueConstraint(fields=('process_run', 'process_step'), name='step_run_run_step_uniq'),
        ),
        migrations.AddConstraint(
            model_name='processsteprun',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('completed_at__isnull', False), ('status', 'COMPLETED'), ('submission__isnull', False)), models.Q(('completed_at__isnull', True), ('status__in', ['LOCKED', 'AVAILABLE']), ('submission__isnull', True)), _connector='OR'), name='step_run_state_data_ck'),
        ),
    ]
