# Generated by Django 5.2.17 on 2026-09-29 13:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0001_initial'),
        ('processes', '0003_remove_processrun_process_run_xor_identity_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='processsteprun',
            name='submission',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='process_step_run', to='forms.formsubmission'),
        ),
    ]
