# Generated by Django 5.2.17 on 2026-09-20 13:13

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Form',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('visibility', models.CharField(choices=[('PUBLIC', 'Public'), ('PRIVATE', 'Private')], default='PUBLIC', max_length=10)),
                ('access_password_hash', models.CharField(blank=True, max_length=128, null=True)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('PUBLISHED', 'Published'), ('CLOSED', 'Closed')], default='DRAFT', max_length=10)),
                ('view_count', models.PositiveBigIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='forms', to='core.category')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='owned_forms', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='FormSubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('form', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='submissions', to='forms.form')),
                ('respondent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='form_submissions', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('question_type', models.CharField(choices=[('TEXT', 'Text'), ('NUMBER', 'Number'), ('SELECT', 'Select'), ('CHECKBOX', 'Checkbox')], max_length=16)),
                ('is_required', models.BooleanField(default=False)),
                ('order', models.PositiveIntegerField()),
                ('max_length', models.PositiveIntegerField(blank=True, null=True)),
                ('min_value', models.DecimalField(blank=True, decimal_places=6, max_digits=18, null=True)),
                ('max_value', models.DecimalField(blank=True, decimal_places=6, max_digits=18, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('form', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='forms.form')),
            ],
        ),
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text_value', models.TextField(blank=True, null=True)),
                ('number_value', models.DecimalField(blank=True, decimal_places=6, max_digits=18, null=True)),
                ('submission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='forms.formsubmission')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='answers', to='forms.question')),
            ],
        ),
        migrations.CreateModel(
            name='QuestionOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=255)),
                ('order', models.PositiveIntegerField()),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='options', to='forms.question')),
            ],
        ),
        migrations.CreateModel(
            name='AnswerOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='selected_options', to='forms.answer')),
                ('option', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='answer_links', to='forms.questionoption')),
            ],
        ),
        migrations.AddIndex(
            model_name='form',
            index=models.Index(fields=['owner', 'status', '-created_at'], name='form_owner_status_created_idx'),
        ),
        migrations.AddConstraint(
            model_name='form',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('access_password_hash__isnull', True), ('visibility', 'PUBLIC')), models.Q(('access_password_hash__isnull', False), ('visibility', 'PRIVATE')), _connector='OR'), name='form_visibility_password_ck'),
        ),
        migrations.AddIndex(
            model_name='formsubmission',
            index=models.Index(fields=['form', '-submitted_at'], name='formsub_form_submitted_idx'),
        ),
        migrations.AddConstraint(
            model_name='question',
            constraint=models.UniqueConstraint(fields=('form', 'order'), name='question_form_order_uniq'),
        ),
        migrations.AddConstraint(
            model_name='question',
            constraint=models.CheckConstraint(condition=models.Q(('order__gte', 1)), name='question_order_gte_1_ck'),
        ),
        migrations.AddConstraint(
            model_name='question',
            constraint=models.CheckConstraint(condition=models.Q(('min_value__isnull', True), ('max_value__isnull', True), ('min_value__lte', models.F('max_value')), _connector='OR'), name='question_numeric_bounds_ck'),
        ),
        migrations.AddConstraint(
            model_name='answer',
            constraint=models.UniqueConstraint(fields=('submission', 'question'), name='answer_submission_question_uniq'),
        ),
        migrations.AddConstraint(
            model_name='questionoption',
            constraint=models.UniqueConstraint(fields=('question', 'order'), name='question_option_order_uniq'),
        ),
        migrations.AddConstraint(
            model_name='questionoption',
            constraint=models.UniqueConstraint(fields=('question', 'label'), name='question_option_label_uniq'),
        ),
        migrations.AddConstraint(
            model_name='questionoption',
            constraint=models.CheckConstraint(condition=models.Q(('order__gte', 1)), name='question_option_order_gte_1_ck'),
        ),
        migrations.AddConstraint(
            model_name='answeroption',
            constraint=models.UniqueConstraint(fields=('answer', 'option'), name='answer_option_pair_uniq'),
        ),
    ]
